# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdf91ac22aba4cd6e4fd760a6fccbcea595fd480de14e9ddfd9b83dc18a00c5427b476bd87f510545f65ccc6ac8ded006113724c538695e9fd1b81c70ea12aa9

test:
  secret_key_base: 6480fe1b1e447a4082ad3f26f085c2e13ad768bbce7dd16c6798e8cab7ef3ed30636a711f5b067dbf8f765132038c42a80e6dc6d8535532359993fff3dc13f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
